export const de = {
  appName: 'Haushaltsauktion',
  nav: {
    start: 'Start',
    tasks: 'Aufgaben',
    history: 'Verlauf',
    account: 'Ich',
    adminSettings: 'Einstellungen',
    adminMembers: 'Benutzer',
    adminTasks: 'Aufgaben',
    adminCategories: 'Kategorien',
    adminRewards: 'Punkte-Shop',
    maintenance: 'Verwaltung',
    back: 'Zurück',
  },
  login: {
    title: 'Haushaltsauktion',
    subtitle: 'Anmelden',
    email: 'Benutzername oder E-Mail',
    password: 'Passwort',
    submit: 'Anmelden',
    submitting: 'Wird angemeldet…',
    error: 'Benutzername oder Passwort stimmt nicht.',
    rateLimited: 'Zu viele Versuche. Bitte später erneut versuchen.',
    forgotPassword: 'Passwort vergessen?',
    registerPrompt: 'Neuen Haushalt einrichten',
  },
  register: {
    title: 'Neuen Haushalt einrichten',
    subtitle: 'Einmalige Ersteinrichtung mit Setup-Token',
    setupToken: 'Setup-Token',
    householdName: 'Haushaltsname',
    adminDisplayName: 'Dein Anzeigename',
    adminEmail: 'Deine E-Mail-Adresse',
    adminPassword: 'Passwort (mind. 8 Zeichen)',
    submit: 'Haushalt erstellen',
    submitting: 'Wird eingerichtet…',
    backToLogin: 'Zurück zur Anmeldung',
    errors: {
      unavailable: 'Die Registrierung ist derzeit nicht verfügbar.',
      forbidden: 'Setup-Token ist ungültig.',
      emailTaken: 'Diese E-Mail-Adresse ist bereits registriert.',
      rateLimited: 'Zu viele Versuche. Bitte später erneut versuchen.',
      generic: 'Der Haushalt konnte nicht angelegt werden.',
    },
  },
  action: {
    volunteer: 'Freiwillig übernehmen',
    accept: 'Aufgabe übernehmen',
    buyout: 'Für {cost} Punkte freikaufen',
    buyoutConfirm: 'Freikauf bestätigen',
    complete: 'Als erledigt markieren',
    release: 'Aufgabe zurückgeben',
    later: 'Später entscheiden',
    cancel: 'Abbrechen',
    retry: 'Erneut versuchen',
    loadMore: 'Mehr laden',
    saveConfig: 'Prüfen & speichern',
    back: 'Zurück',
  },
  buyout: {
    heading: 'Freikauf',
    /** §31 — die fünf Werte, die vor einem Freikauf sichtbar sein müssen. */
    balanceBefore: 'Dein Punktestand',
    cost: 'Freikaufkosten',
    balanceAfter: 'Punktestand danach',
    valueBefore: 'Aufgabenwert jetzt',
    valueAfter: 'Aufgabenwert danach',
    disabled: 'Freikaufen nicht möglich: {reason}',
    disabledUnknown: 'Freikaufen ist gerade nicht möglich.',
    reasons: {
      BUYOUT_DISABLED_GLOBALLY: 'Freikauf ist deaktiviert',
      BUYOUT_DISABLED_FOR_TASK: 'Für diese Aufgabe deaktiviert',
      NOT_RANDOM_ASSIGNMENT: 'Nur bei Zufallszuweisung möglich',
      INSUFFICIENT_POINTS: 'Zu wenig Punkte',
      WEEKLY_LIMIT_REACHED: 'Wöchentliches Limit erreicht',
      CONSECUTIVE_LIMIT_REACHED: 'Zu viele Freikäufe hintereinander',
      VALUE_CAP_REACHED: 'Maximaler Aufgabenwert erreicht',
      ASSIGNMENT_CLOSED: 'Zuweisung bereits geschlossen',
    },
  },
  dashboard: {
    greeting: 'Hallo {name}',
    balance: 'Dein Punktestand',
    myTasks: 'Meine Aufgaben',
    available: 'Freiwillig verfügbar',
    household: 'Familie',
    openTasks: 'Offen im Haushalt',
    members: 'Mitglieder',
    currentValue: 'Gesamtwert offen',
    recent: 'Kürzlich erledigt',
    ledgerLink: 'Punktekonto',
    allTasks: 'Alle',
    /** §31 / §6.12 — aktive Trank-Effekte, mit Restzeit/-ladungen sichtbar
     * bevor gehandelt wird. */
    activeEffects: {
      heading: 'Aktive Tränke',
      immunity: 'Aufgaben-Immunität: noch {remaining}',
      multiplier: 'Belohnungs-Multiplikator ×{value}: noch {charges} von {total}, {remaining}',
    },
    reject: {
      trigger: 'Ablehnen',
      rejectedBadge: 'abgelehnt',
      title: 'Erledigung ablehnen',
      intro: 'Die Erledigung von „{task}“ durch {member} wird als nicht zufriedenstellend abgelehnt.',
      whoHeading: 'Wessen Erledigung ablehnen?',
      consequenceWithPoints: 'Dabei werden {points} Punkte von {member} zurückgebucht.',
      consequenceNoPoints: 'Für diese Erledigung wurden keine Punkte vergeben — es gibt nichts zurückzubuchen.',
      outcomeHeading: 'Was passiert mit der Aufgabe?',
      outcomeReassign: 'Zurück an {member}',
      outcomeReassignHint: '{member} muss die Aufgabe nochmal machen. Eine ordentliche Nacherledigung zahlt sich normal aus.',
      outcomeMarket: 'Zurück auf den Markt',
      outcomeMarketHint: 'Die Aufgabe wird für alle wieder als freiwillig verfügbar angeboten.',
      reason: 'Grund (optional)',
      confirm: 'Ablehnung bestätigen',
      success: 'Die Erledigung wurde abgelehnt.',
      errors: {
        alreadyHandled: 'Diese Erledigung wurde bereits bearbeitet.',
        generic: 'Das hat nicht funktioniert.',
      },
    },
  },
  task: {
    title: 'Aufgabe',
    currentValue: 'Aktueller Wert',
    baseValue: 'Basiswert {value}',
    buyoutCount: '×{count} freigekauft',
    dueToday: 'fällig heute',
    dueTomorrow: 'fällig morgen',
    dueSince: 'fällig seit {when}',
    due: 'fällig {when}',
    estimatedMinutes: 'ca. {minutes} Min',
    assignedTo: 'an {name}',
    assignmentKind: {
      VOLUNTARY: 'freiwillig',
      RANDOM: 'zufällig',
    },
    /** Multi-worker-tasks (Phase 4). Only shown when `workerCount > 1`. */
    slotsOccupied: '{occupied}/{total} besetzt',
    since: 'seit {time}',
    status: {
      AVAILABLE: 'verfügbar',
      ASSIGNED: 'zugewiesen',
      COMPLETED: 'erledigt',
      CANCELLED: 'abgebrochen',
      PAUSED: 'pausiert',
      EXPIRED: 'abgelaufen',
      OVERDUE: 'überfällig',
      DRAFT: 'Entwurf',
    },
    noTasks: 'Gerade nichts offen.',
    noAssigned: 'Dir ist gerade nichts zugewiesen.',
    noHeld: 'Du hast gerade keine Aufgabe übernommen.',
    allHouseholdTasksTab: 'Alle Aufgaben',
    noHouseholdTasks: 'Gerade ist nichts offen.',
    assignedYou: 'Dir zugewiesen',
    assignedOther: 'Jemandem sonst zugewiesen',
    /** Multi-worker-tasks (Phase 4): per co-assignee row when >1 active slot. */
    assignedNamed: '{name} zugewiesen',
    adminUnassign: {
      trigger: 'Zuweisung aufheben',
      title: 'Zuweisung aufheben',
      intro: 'Die Zuweisung von „{task}“ an {member} wird aufgehoben. Die Aufgabe wird danach wieder freiwillig verfügbar.',
      reason: 'Grund (optional)',
      confirm: 'Aufheben bestätigen',
      errors: {
        alreadyHandled: 'Diese Zuweisung wurde bereits bearbeitet.',
        generic: 'Das hat nicht funktioniert.',
      },
    },
  },
  confirm: {
    acceptTitle: 'Aufgabe übernehmen',
    buyoutTitle: 'Freikauf bestätigen',
    freshness: 'Preis vom Server bestätigt · {time}',
    balance: 'Dein Punktestand',
    value: 'Aufgabenwert',
    completeTitle: 'Erledigung bestätigen',
  },
  blocked: {
    title: 'Freikauf nicht möglich',
    insufficientPoints:
      'Du hast {balance} Punkte, der Freikauf kostet {cost}. In diesem Haushalt sind negative Punktestände nicht erlaubt.',
    minimumBalance: 'Dein Punktestand darf nicht unter {min} fallen.',
    weeklyLimit:
      'Du hast diese Woche schon {n} Aufgaben abgegeben. Mehr sind nicht vorgesehen.',
    consecutiveLimit:
      'Nach {n} Freikäufen hintereinander ist erst wieder eine erledigte Aufgabe nötig.',
    taskDisabled: 'Für diese Aufgabe ist das Abgeben abgeschaltet.',
    householdDisabled: 'In diesem Haushalt ist Freikaufen abgeschaltet.',
  },
  quote: {
    changedTitle: 'Der Preis hat sich geändert',
    changedBody:
      'Angezeigt war ein Freikauf für {oldCost} Punkte. Er kostet jetzt {newCost} Punkte{reason}.',
    reasonBuyout: ', weil sich in der Zwischenzeit jemand freigekauft hat',
    reasonConfig: ', weil eine Regel geändert wurde',
    confirmNew: 'Zum neuen Preis freikaufen',
  },
  history: {
    title: 'Verlauf',
    empty: 'Noch nichts passiert. Sobald eine Aufgabe angeboten wird, steht es hier.',
    eventTypes: {
      OFFERED: '{task} wurde angeboten — Wert {value}',
      NO_VOLUNTEER: 'Keine freiwillige Übernahme für {task}',
      RANDOMLY_ASSIGNED: 'Zufallszuweisung von {task} an {member}',
      ASSIGNMENT_ACCEPTED: '{member} hat die zugeloste Aufgabe {task} übernommen',
      VOLUNTEERED: '{task} freiwillig von {member} übernommen',
      BOUGHT_OUT: '{member} kaufte sich von {task} für {cost} Punkte frei',
      VALUE_INCREASED: 'Neuer Wert für {task}: {value}',
      COMPLETED: '{task} von {member} erledigt',
      POINTS_AWARDED: '{member} erhält {points} Punkte für {task}',
      VALUE_RESET: 'Aufgabenwert von {task} auf {to} zurückgesetzt',
      RELEASED: '{member} hat {task} zurückgegeben',
      REVOKED: 'Zuweisung von {task} an {member} wurde aufgehoben',
      EXPIRED: 'Angebot für {task} abgelaufen',
      CONFIG_CHANGED: '{member} hat eine Regel geändert: {key}',
      CREATED: '{task} angelegt — Wert {value}',
      CONSTRAINT_RELAXED: 'Regel ausgesetzt für {task}: {constraint}',
      NO_ELIGIBLE_CANDIDATES: 'Keine geeigneten Kandidaten für {task}',
      PAUSED: '{task} pausiert',
      RESUMED: '{task} fortgesetzt',
      POINTS_CLAWED_BACK: '{member} hat {points} Punkte für {task} zurückgegeben',
      COMPLETION_REJECTED: 'Erledigung von {task} durch {member} wurde abgelehnt',
      REOPENED_TO_ASSIGNEE: '{task} wurde {member} zur Nacherledigung zurückgegeben',
      RE_OFFERED: '{task} wurde erneut angeboten — Wert {value}',
      CANCELLED: '{task} wurde abgebrochen',
    },
  },
  notifications: {
    title: 'Benachrichtigungen',
    empty: 'Keine Benachrichtigungen.',
    markAllRead: 'Alle als gelesen markieren',
    unreadBadge: '{n} ungelesen',
    types: {
      TASK_AVAILABLE: '„{task}“ ist jetzt freiwillig verfügbar — aktueller Wert {value}',
      TASK_ASSIGNED: 'Dir wurde „{task}“ zufällig zugewiesen — aktueller Wert {value}',
      TASK_TAKEN: 'Du hast „{task}“ übernommen — aktueller Wert {value}',
      TASK_DUE_SOON: '„{task}“ wird bald fällig',
      TASK_COMPLETED: '„{task}“ wurde von {by} erledigt',
      TASK_VALUE_INCREASED: '„{task}“: Wert ist von {from} auf {to} gestiegen',
      ADMIN_NO_CANDIDATES: 'Für „{task}“ gab es keine geeigneten Kandidaten',
    },
  },
  fairness: {
    trigger: 'Warum wurde ich ausgewählt?',
    title: 'Warum ich?',
    loading: 'Wird geladen …',
    availableCount: 'Für diese Aufgabe waren {n} Personen verfügbar.',
    excludedLabel: 'ausgeschlossen: {reason}',
    weightsHeading: 'Gewichtung der übrigen Personen',
    weight: 'Gewicht {value}',
    selected: 'ausgewählt',
    closing: 'Die Auswahl erfolgte zufällig, gewichtet nach diesen Werten.',
    relaxedNote: 'Die Regel „{constraint}“ musste ausgesetzt werden — sonst wäre niemand übrig geblieben.',
    strategies: {
      WEIGHTED_FAIRNESS:
        'Ausgleichende Gewichtung — wer zuletzt seltener zugelost wurde, wird wahrscheinlicher ausgewählt.',
      PURE_RANDOM: 'Reiner Zufall — alle berechtigten Personen sind gleich wahrscheinlich.',
      LEAST_ASSIGNED_FIRST: 'Wer bisher am seltensten zugelost wurde, kommt zuerst.',
      WEIGHTED_RANDOM: 'Gewichteter Zufall nach den eingestellten Kriterien.',
    },
    /** Deckt exakt `EligibilityReason` aus packages/shared/src/domain/reasons.ts ab. */
    reasons: {
      MEMBER_INACTIVE: 'ist derzeit nicht aktiv',
      MEMBER_ABSENT: 'ist gerade abwesend',
      EXCLUDED_FROM_TASK: 'ist für diese Aufgabe ausgenommen',
      NOT_IN_ALLOWLIST: 'ist nicht für diese Aufgabe zugelassen',
      CATEGORY_EXCLUDED: 'ist für diese Kategorie ausgenommen',
      RANDOM_ASSIGNMENT_CAP_REACHED: 'hat das Limit für Zuweisungen erreicht',
      IMMEDIATE_REASSIGNMENT_BLOCKED: 'hat diese Aufgabe zuletzt erledigt',
      /** rule 8, intake "points-shop-virtual-gamification-items". */
      MEMBER_IMMUNE: 'hat gerade einen Immunitätstrank aktiv',
    },
    /** Deckt `RelaxableConstraint` aus packages/shared/src/domain/reasons.ts ab. */
    constraints: {
      IMMEDIATE_REASSIGNMENT: 'keine sofortige Wiederzuweisung',
      ASSIGNMENT_CAP: 'Obergrenze für Zufallszuweisungen',
    },
  },
  install: {
    prompt: 'Haushaltsauktion als App installieren?',
    action: 'Installieren',
    dismiss: 'Nicht jetzt',
  },
  update: {
    prompt: 'Eine neue Version ist verfügbar.',
    action: 'Aktualisieren',
    dismiss: 'Später',
  },
  account: {
    title: 'Ich',
    balance: 'Punktestand',
    ledger: 'Punktekonto',
    logout: 'Abmelden',
    household: 'Haushalt',
    adminEntry: 'Verwaltung',
    settings: 'Einstellungen',
    rewardsShop: 'Punkte-Shop',
  },
  todoist: {
    title: 'Todoist',
    // §31: keine versteckten Regeln. Beide Sätze stehen VOR dem Eingabefeld.
    intro:
      'Neu zugewiesene oder freiwillig übernommene Aufgaben erscheinen automatisch in deinem Todoist.',
    oneWayWarning:
      'Wichtig: Ein Häkchen in Todoist erledigt die Aufgabe hier NICHT. Erledigt wird sie nur in der Haushaltsauktion.',
    tokenScopeWarning:
      'Dein persönliches Todoist-Token gibt vollen Zugriff auf dein Todoist-Konto. Es wird verschlüsselt gespeichert und nie wieder angezeigt.',
    tokenLabel: 'Persönliches API-Token',
    tokenHelp: 'Zu finden in Todoist unter Einstellungen → Integrationen → Entwickler.',
    connect: 'Verbinden',
    connecting: 'Wird verbunden…',
    connected: 'Verbunden',
    disconnect: 'Trennen',
    disconnectConfirm:
      'Wirklich trennen? Wir versuchen zuerst, deine offenen Todoist-Aufgaben zu schliessen. Was wir nicht erreichen, bleibt in Todoist stehen und wird von der Haushaltsauktion nicht mehr angefasst.',
    test: 'Verbindung testen',
    testing: 'Wird geprüft…',
    testOk: 'Verbindung funktioniert.',
    project: 'Projekt',
    projectInbox: 'Posteingang',
    projectHint:
      'Nur in deinem eigenen Todoist-Konto sichtbar. Ein gemeinsames Haushalts-Projekt gibt es nicht — wollt ihr Aufgaben gebündelt sehen, legt jede Person ein Projekt mit demselben Namen im eigenen Konto an und wählt es hier aus.',
    triggers: 'Wann eine Todoist-Aufgabe entsteht',
    triggerRandom: 'Bei zufälliger Zuweisung',
    triggerVoluntary: 'Bei freiwilliger Übernahme',
    invalidCredentials:
      'Todoist hat dein Token abgelehnt. Bitte neu verbinden — bis dahin werden keine Aufgaben übertragen.',
    unavailable: 'Todoist ist gerade nicht erreichbar. Bitte später erneut versuchen.',
    lastSuccess: 'Zuletzt erfolgreich',
    saveFailed: 'Konnte nicht gespeichert werden.',
  },
  ledger: {
    title: 'Punktekonto',
    empty: 'Noch keine Punktebewegungen.',
    type: {
      VOLUNTARY_TASK_REWARD: 'Freiwillige Aufgabe',
      BUYOUT: 'Freikauf',
      MANUAL_ADJUSTMENT: 'Manuelle Anpassung',
      DECAY: 'Punktverfall',
      BONUS: 'Bonus',
      PENALTY: 'Strafe',
      CORRECTION: 'Korrektur',
      STREAK_BONUS: 'Serien-Bonus',
      REWARD_REDEMPTION: 'Punkte-Shop',
    },
  },
  rewards: {
    title: 'Punkte-Shop',
    balance: 'Dein Punktestand',
    empty: 'Aktuell keine Belohnungen verfügbar.',
    buy: 'Kaufen',
    confirmTitle: 'Kauf bestätigen',
    balanceBefore: 'Dein Punktestand',
    cost: 'Kosten',
    balanceAfter: 'Punktestand danach',
    confirm: 'Kauf bestätigen',
    cancel: 'Abbrechen',
    purchaseSuccess: 'Belohnung gekauft — ein Admin erfüllt sie als Nächstes.',
    /** Virtuelle Effekte werden sofort wirksam — keine Admin-Erfüllung. */
    purchaseSuccessImmunity: 'Trank gewirkt — du bist jetzt für {duration} von der Zufallsvergabe ausgenommen.',
    purchaseSuccessMultiplier: 'Trank gewirkt — die nächsten {charges} freiwilligen Erledigungen zählen ×{multiplier}, {duration} lang.',
    virtualEffectBadge: 'Sofort wirksam',
    effectSummary: {
      IMMUNITY: 'Macht dich für {duration} unsichtbar für die Zufallsvergabe. Freiwillig übernehmen bleibt möglich.',
      MULTIPLIER: 'Die nächsten {charges} freiwilligen Erledigungen zählen ×{multiplier}, {duration} lang.',
    },
    errors: {
      disabled: 'Der Punkte-Shop ist gerade deaktiviert.',
      insufficientPoints: 'Du hast {balance} Punkte, die Belohnung kostet {cost}.',
      generic: 'Das hat nicht funktioniert.',
    },
  },
  components: {
    duration: {
      unitLabel: 'Einheit',
      minutes: 'Minuten',
      hours: 'Stunden',
      days: 'Tage',
    },
    timezoneNote: 'Zeiten gelten in: {timezone}',
    dismiss: 'Schließen',
  },
  admin: {
    title: 'Verwaltung',
    rules: 'Regeln & Werte',
    tasks: 'Aufgaben',
    assignment: 'Vergabe',
    audit: 'Protokoll',
    save: 'Speichern',
    preview: 'Vorschau',
    runSweep: 'Zufallszuweisung jetzt ausführen',
    dryRun: 'Probelauf',
    version: 'Version',
    updatedAt: 'Zuletzt geändert',
    settingsEntryHint: 'Zuweisung, Freiwillige Übernahme, Freikauf, Wertsteigerung und Aufgaben-Grundwerte.',
    settingsEntryButton: 'Einstellungen öffnen',
    sections: {
      assignment: 'Zuweisung',
      voluntary: 'Freiwillige Übernahme',
      buyout: 'Freikauf',
      valueIncrease: 'Wertsteigerung',
      tasks: 'Aufgaben',
      members: 'Mitglieder',
      taskDefinitions: 'Aufgaben verwalten',
      categories: 'Kategorien',
      rewards: 'Punkte-Shop',
      redemptions: 'Einlösungen',
    },
    members: {
      title: 'Mitglieder',
      addButton: 'Mitglied hinzufügen',
      addTitle: 'Neues Mitglied',
      email: 'E-Mail-Adresse',
      displayName: 'Anzeigename',
      password: 'Passwort (optional)',
      passwordHint: 'Leer lassen für ein zufällig erzeugtes Passwort.',
      role: 'Rolle',
      roleValues: {
        MEMBER: 'Mitglied',
        ADMIN: 'Admin',
      },
      active: 'Aktiv',
      maxRandomAssignmentsPerWeek: 'Zufallslimit/Woche',
      maxRandomAssignmentsPerWeekHint: 'Leer lassen für kein Limit.',
      balance: 'Punktestand',
      balanceReadonlyHint: 'Nur lesbar.',
      save: 'Speichern',
      create: 'Anlegen',
      cancel: 'Abbrechen',
      empty: 'Noch keine Mitglieder.',
      filterLabel: 'Mitglieder filtern',
      filterPlaceholder: 'Name oder E-Mail durchsuchen…',
      filterEmpty: 'Keine Mitglieder gefunden.',
      restrictionsButton: 'Einschränkungen',
      restrictionsTitle: 'Einschränkungen: {name}',
      excludedCategories: 'Ausgeschlossene Kategorien',
      excludedCategoriesEmpty: 'Keine Kategorien angelegt.',
      excludedTasks: 'Ausgeschlossene Aufgaben',
      excludedTasksEmpty: 'Keine Aufgaben angelegt.',
      absences: 'Abwesenheiten',
      absenceStart: 'Von',
      absenceEnd: 'Bis',
      absenceReason: 'Grund (optional)',
      addAbsence: 'Abwesenheit hinzufügen',
      removeAbsence: 'Entfernen',
      saveRestrictions: 'Einschränkungen speichern',
      saved: 'Gespeichert.',
      createSuccess: 'Mitglied wurde angelegt.',
      resetPasswordButton: 'Passwort zurücksetzen',
      resetPasswordTitle: 'Neues Passwort für {name}',
      resetPasswordHint: 'Leer lassen für ein zufällig erzeugtes Passwort.',
      resetPasswordNewPassword: 'Neues Passwort (optional)',
      resetPasswordConfirm: 'Passwort setzen',
      resetPasswordSuccess: 'Passwort wurde geändert. Alle bisherigen Sitzungen dieser Person wurden beendet.',
      temporaryPasswordHeading: 'Passwort — jetzt notieren',
      temporaryPasswordHint: 'Dieses Passwort wird nur einmal angezeigt und danach nicht mehr abrufbar sein.',
      temporaryPasswordClose: 'Notiert, schließen',
      adjustPointsButton: 'Punkte anpassen',
      adjustPointsTitle: 'Punkte anpassen: {name}',
      adjustAmountLabel: 'Betrag',
      adjustAmountHint: 'Positiv für eine Gutschrift, negativ für einen Abzug.',
      adjustReasonLabel: 'Begründung',
      adjustSubmit: 'Anpassen',
      adjustSuccess: 'Punkte wurden angepasst.',
      errors: {
        alreadyMember: 'Diese Person ist bereits Mitglied.',
        lastAdmin: 'Der letzte Admin kann nicht entfernt werden.',
        invalidAbsenceRange: 'Abwesenheit: Ende muss nach Beginn liegen.',
        invalidAmount: 'Betrag muss eine ganze Zahl ungleich 0 sein.',
        reasonRequired: 'Eine Begründung ist erforderlich.',
        generic: 'Das hat nicht funktioniert.',
      },
    },
    taskDefinitions: {
      title: 'Aufgaben',
      addButton: 'Aufgabe hinzufügen',
      addTitle: 'Neue Aufgabe',
      editTitle: 'Aufgabe bearbeiten',
      titleField: 'Titel',
      description: 'Beschreibung',
      category: 'Kategorie',
      noCategory: 'Keine Kategorie',
      baseValue: 'Basiswert',
      estimatedMinutes: 'Geschätzte Dauer',
      buyoutEnabled: 'Freikauf erlaubt',
      active: 'Aktiv',
      /** Multi-worker-tasks (Phase 4): how many people can hold this task at once. */
      workerCountMode: 'Helfer-Modus',
      workerCountModes: {
        EXACTLY: 'Genau',
        AT_LEAST: 'Mindestens',
        AT_MOST: 'Höchstens',
      },
      workerCount: 'Anzahl Helfer',
      workerCountSummary: '{mode} {count}',
      save: 'Speichern',
      create: 'Anlegen',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      archive: 'Archivieren',
      reactivate: 'Reaktivieren',
      empty: 'Noch keine Aufgaben.',
      filterLabel: 'Aufgaben filtern',
      filterPlaceholder: 'Aufgaben durchsuchen…',
      filterEmpty: 'Keine Aufgaben gefunden.',
      includeArchived: 'Archivierte einschließen',
      archivedBadge: 'archiviert',
      createSuccess: 'Aufgabe wurde angelegt.',
      saved: 'Gespeichert.',
      archivedSuccess: 'Aufgabe wurde archiviert.',
      reactivatedSuccess: 'Aufgabe wurde reaktiviert.',
      materializeButton: 'Jetzt anbieten',
      materializedSuccess: 'Neue Instanz wurde erstellt.',
      eligibilityButton: 'Berechtigung',
      eligibilityTitle: 'Berechtigung: {title}',
      eligibilityHint:
        'Standardmäßig sind alle aktiven Mitglieder berechtigt. „Nur diese Mitglieder“ beschränkt die Aufgabe, „Ausschließen“ nimmt einzelne Mitglieder heraus.',
      eligibilityIncluded: 'Nur diese Mitglieder zulassen',
      eligibilityIncludedEmpty: 'Keine Einschränkung — alle aktiven Mitglieder sind zulässig.',
      eligibilityExcluded: 'Diese Mitglieder ausschließen',
      saveEligibility: 'Berechtigung speichern',
      recurrence: {
        title: 'Wiederholung',
        type: 'Typ',
        types: {
          ONCE: 'Einmalig',
          DAILY: 'Täglich',
          WEEKDAYS: 'Bestimmte Wochentage',
          WEEKLY: 'Wöchentlich',
          EVERY_N_DAYS: 'Alle N Tage',
          MONTHLY: 'Monatlich',
          MANUAL: 'Manuell',
        },
        interval: 'Intervall (Tage)',
        weekdays: 'Wochentage',
        weekdayLabels: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'] as string[],
        dayOfMonth: 'Tag des Monats',
        timeOfDay: 'Uhrzeit (HH:mm)',
        dueOffsetMinutes: 'Fällig nach',
        summary: {
          ONCE: 'Einmalig',
          DAILY: 'Täglich',
          WEEKLY: 'Wöchentlich',
          MANUAL: 'Manuell',
          WEEKDAYS: '{days}',
          EVERY_N_DAYS: 'Alle {n} Tage',
          MONTHLY: 'Monatlich (Tag {day})',
        },
      },
      errors: {
        hasOpenInstances:
          'Es gibt noch {count} offene Instanz(en) dieser Aufgabe. Erst erledigen oder abbrechen, bevor sie archiviert werden kann.',
        generic: 'Das hat nicht funktioniert.',
      },
      instances: {
        title: 'Laufende Instanzen',
        empty: 'Aktuell keine offenen Instanzen.',
        assignedTo: '{name} ({kind})',
        unassigned: 'niemand',
        kindLabels: {
          VOLUNTARY: 'freiwillig',
          RANDOM: 'zufällig',
        },
      },
    },
    categories: {
      title: 'Kategorien',
      addButton: 'Kategorie hinzufügen',
      addTitle: 'Neue Kategorie',
      name: 'Name',
      color: 'Farbe',
      dragHandle: 'Zum Sortieren ziehen',
      save: 'Speichern',
      create: 'Anlegen',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      empty: 'Noch keine Kategorien.',
      filterLabel: 'Kategorien filtern',
      filterPlaceholder: 'Kategorien durchsuchen…',
      filterEmpty: 'Keine Kategorien gefunden.',
      createSuccess: 'Kategorie wurde angelegt.',
      saved: 'Gespeichert.',
      deletedSuccess: 'Kategorie wurde gelöscht.',
      errors: {
        inUse: 'Kategorie wird noch von {count} Aufgabe(n) verwendet.',
        generic: 'Das hat nicht funktioniert.',
      },
    },
    rewards: {
      title: 'Punkte-Shop',
      addButton: 'Belohnung hinzufügen',
      addTitle: 'Neue Belohnung',
      editTitle: 'Belohnung bearbeiten',
      titleField: 'Titel',
      description: 'Beschreibung',
      cost: 'Punktekosten',
      active: 'Aktiv',
      save: 'Speichern',
      create: 'Anlegen',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      empty: 'Noch keine Belohnungen.',
      createSuccess: 'Belohnung wurde angelegt.',
      saved: 'Gespeichert.',
      /** intake "points-shop-virtual-gamification-items". */
      kind: 'Art',
      kindOptions: {
        MANUAL_FULFILLMENT: 'Reale Belohnung (Admin erfüllt)',
        VIRTUAL_EFFECT: 'Virtueller Effekt (sofort wirksam)',
      },
      effectType: 'Effekt',
      effectTypeOptions: {
        IMMUNITY: 'Immunität (Zufallsvergabe aussetzen)',
        MULTIPLIER: 'Belohnungs-Multiplikator',
      },
      effectDurationMinutes: 'Dauer (Minuten)',
      effectCharges: 'Ladungen',
      effectMultiplier: 'Multiplikator',
      virtualEffectBadge: 'Virtueller Effekt',
      errors: {
        generic: 'Das hat nicht funktioniert.',
      },
    },
    redemptions: {
      title: 'Ausstehende Einlösungen',
      empty: 'Keine offenen Einlösungen.',
      purchasedAt: 'Gekauft am {when}',
      fulfill: 'Erfüllt',
      fulfilledSuccess: 'Als erfüllt markiert.',
      errors: {
        alreadyHandled: 'Diese Einlösung wurde bereits bearbeitet.',
        generic: 'Das hat nicht funktioniert.',
      },
    },
    fields: {
      offerDurationMinutes: 'Angebotsdauer',
      leadMinutesBeforeDue: 'Zufallszuweisung ab (Minuten vor Fälligkeit)',
      leadMinutesBeforeDueHint:
        'Aufgaben ohne Fälligkeit werden nie automatisch zugelost. Aufgaben mit Fälligkeit erst, sobald weniger als diese Zeitspanne bis zur Fälligkeit verbleibt.',
      strategy: 'Strategie',
      preventImmediateReassignment: 'Keine sofortige Wiederzuweisung',
      relaxConstraintsWhenNoCandidates: 'Einschränkungen aufweichen, falls nötig',
      rewardEnabled: 'Punkte für freiwillige Aufgaben',
      rewardMultiplier: 'Belohnungsmultiplikator',
      rewardTiming: 'Belohnungszeitpunkt',
      allowRelease: 'Zurückgeben erlauben',
      todoistEnabled: 'Todoist-Integration für diesen Haushalt erlauben',
      todoistUnavailable:
        'Dieser Server ist für Todoist nicht eingerichtet (fehlender Schlüssel). Solange das so ist, kann sich kein Mitglied verbinden — die Integration lässt sich hier nicht aktivieren.',
      todoistEnabledHint:
        'Jedes Mitglied verbindet danach sein eigenes Todoist-Konto unter „Ich“. Wird die Integration wieder ausgeschaltet, werden offene Todoist-Aufgaben des Haushalts geschlossen; beim erneuten Einschalten werden sie neu angelegt. Ein gemeinsames Haushalts-Projekt gibt es nicht — jedes Konto ist getrennt. Wer Aufgaben trotzdem gebündelt sehen möchte, legt in jedem Konto ein Projekt mit demselben Namen an und wählt es dort einzeln aus.',
      todoistPriority: 'Priorität neu angelegter Todoist-Aufgaben',
      todoistPriorityDefault: 'Kein Wert (Todoist-Standard)',
      todoistPriorityUrgent: 'Dringend (Todoist P1)',
      todoistPriorityHigh: 'Hoch (Todoist P2)',
      todoistPriorityMedium: 'Mittel (Todoist P3)',
      todoistPriorityNormal: 'Normal (Todoist P4)',
      todoistPriorityHint:
        'Gilt für neue Aufgaben, die diese Anwendung in Todoist anlegt. Ohne Auswahl setzt Todoist selbst die Standardpriorität.',
      enabled: 'Aktiviert',
      allowNegativeBalance: 'Negativen Kontostand erlauben',
      minimumBalance: 'Mindestguthaben für Freikauf',
      multiplier: 'Multiplikator',
      minimumIncrease: 'Minimale Steigerung',
      maximumValue: 'Maximaler Wert',
      maxOpenInstancesPerDefinition: 'Max. offene Instanzen pro Aufgabe',
    },
    timing: {
      ON_ACCEPT: 'bei Übernahme',
      ON_COMPLETE: 'bei Erledigung',
    },
    sweepResult:
      'Ergebnis: {materialized} neu, {published} veröffentlicht, {assigned} zugewiesen, {expired} abgelaufen, {skipped} übersprungen',
    saved: 'Konfiguration gespeichert.',
    saveFailed: 'Speichern fehlgeschlagen.',
  },
  error: {
    title: 'Fehler',
    loadFailed: 'Die Daten konnten nicht geladen werden.',
    forbidden: 'Dafür fehlen dir die Rechte.',
    notFound: 'Diese Aufgabe gibt es nicht mehr.',
    taskTaken: '{name} war schneller — die Aufgabe ist schon vergeben.',
    offline: 'Offline — du kannst Aufgaben ansehen, aber gerade nichts übernehmen.',
  },
};

export type Strings = typeof de;
